### ISSUE TITLE
Collector configuration doc is missing new service.telemetry subsection

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry.io#1181]
**What needs to be changed?**
Update collector configuration doc with new service.telemetry section

**What is the name + path of the page that needs changed?**
https://opentelemetry.io/docs/collector/configuration/#service

**Additional context**
With [#4069 in opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector/pull/4069) there is now a new subsection, `telemetry`, allowed under `service`.  The docs should be updated with details on all the new configuration allowed under the `telemetry` subsection.

**Comment by jpkrohling** [comment]
@TylerHelmuth, would you be open to sending in a PR? If so, just ping me and I'll review it.

**Comment by TylerHelmuth** [comment]
> @TylerHelmuth, would you be open to sending in a PR? If so, just ping me and I'll review it.

I'll need to brush up on the new telemetry config code in the collector but I can take a shot.

**Comment by jpkrohling** [comment]
If you need a primer, this is how you can configure it:

```
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:

processors:

extensions:

service:
  extensions:
  pipelines:
    traces:
      receivers: [otlp]
      processors:
      exporters: [logging]
  telemetry:
    logs:
      level: debug
      initial_fields:
        service: my-instance
    metrics:
      level: detailed
```

The code with all the available options can be seen here:
https://github.com/open-telemetry/opentelemetry-collector/blob/7666eb04c30e5cfd750db9969fe507562598f0ae/config/service.go#L35-L111
