### ISSUE TITLE
Document the new sub command "components"

### ISSUE THREAD

**Issue by Chinwendu20** [open-telemetry/opentelemetry.io#2072]
**What needs to be changed?**
A new sub-command has been added to the collector core. Lnk to merged [PR](https://github.com/open-telemetry/opentelemetry-collector/pull/6322)

**Additional context**
The command displays the components available in a given distribution. You can use the update in the readme as a guide for documentation. This is an example of how the command works:

```bash
   ./otelcorecol components
```
Sample output:

```yaml

buildinfo:
   command: otelcorecol
   description: Local OpenTelemetry Collector binary, testing only.
   version: 0.62.1-dev
receivers:
   - otlp
processors:
   - memory_limiter
   - batch
exporters:
   - otlp
   - otlphttp
   - logging
extensions:
   - zpages
   - memory_ballast


```
