### ISSUE TITLE
Follow up on collector deployment

### ISSUE THREAD

**Issue by mhausenblas** [open-telemetry/opentelemetry.io#2692]
In https://github.com/open-telemetry/opentelemetry.io/pull/2498 we parked a few things that should be addressed ASAP in a follow-up PR. They are:

Changes for follow up PR for https://github.com/open-telemetry/opentelemetry.io/pull/2498

## In `agent.md`

Expand on the cons for the agent pattern, that is, flesh out the following:

- Scalability (human and load-wise)
- Inflexible

## In `best-practices.md`

* replace Jaeger exporter with OTLP exporter
* simplify by configuring both exporters for the same pipeline in `metrics/prod`
* make sure we use attributes covered by the semantic conventions across the doc

Replace:

```
processors:
  attributes:
    actions:
      - key: cluster
        value: eu-west-1
        action: upsert
  metricstransform:
    transforms:
      - include: otelcol_process_uptime
        action: update
        operations:
          - action: add_label
            new_label: cluster
            new_value: eu-west-1
```

With:

```
transform:
  error_mode: ignore
  trace_statements:
    - context: span
      statements:
        - set(attributes["cluster"], "eu-west-1") 
  metric_statements:
    - context: datapoint
      statements:
        - set(attributes["cluster"], "eu-west-1") where metric.name == "otelcol_process_uptime
```

## In `collector/_index.md`

Replace `#when-to-use-a-collector` with one that calls out all the deployment patterns and mentions that there is one for no collector and what the advantages/disadvantages are.
