### ISSUE TITLE
Figur out how to do "time-boxed" entries to the banner

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#4380]
In our [banner](https://github.com/open-telemetry/opentelemetry.io/blob/main/layouts/partials/banner.md) we most entries are time-bound (e.g KubeCon, GC-election, an end user SIG event, etc.), and sometimes we forget about those entries and they stay in the banner for way to long. 

I suggest that we add a feature where we time-box those entries with some hugo code, e.g. something like

```
{{- if (today <= enddate) -}}
Here is my banner entry that is only valid until enddate
{{- end -}}
```

Using [time functions](https://gohugo.io/functions/time/) this should be fairly easy to figure out. There are 2 advanced features we might doing at the same time:

* Move the banner entries themselves into a data file, so people can just append them to a list (and we can update previous entries more easily). Disadvantage is that this list may grow over time containing a lot of outdated stuff
* Verify that 2 entries at max are shown. I am not 100% sure exactly how we want to enforce this best.

**Comment by ricardoamaro** [comment]
To ensure that banner entries are only displayed until their relevant end date, we could define the End Date for each Banner entry.
If we move the banner entries to a data file, each entry could look something like this in a YAML file: 
eg. `data/banners.yml`

```yaml
- title: "OTel Community Day"
  url: "https://sessionize.com/OTel-Community-Day/"
  message: "Join us for OTel Community Day on June 25th!"
  endDate: 2023-06-25

- title: "OTel and Prometheus Survey"
  url: "https://forms.gle/bZAG9f7udoJsjZUG9"
  message: "Help improve OTel and Prometheus interoperability: complete our survey by May 31"
  endDate: 2023-05-31
```

Then we will need to modify the banner display logic in `banner.md` partial to loop through the banner entries and check the current date against each entry's `endDate`. Something on these lines:

```
{{ if .Params.show_banner }}
  {{ $currentDate := now.Format "2006-01-02" }}
  {{ range $.Site.Data.banners }}
    {{ if le $currentDate .endDate }}
      <div class="o-banner">
        <i class="fas fa-bullhorn"></i> <a href="{{ .url }}">{{ .message }}</a>
      </div>
    {{ end }}
  {{ end }}
{{ end }}
```

A consideration to take is that over time, `banners.yml` file may grow with outdated entries. Periodically, we will need to clean it or create a script to automatically remove past entries.

Opinions, thoughts, suggestions?

**Comment by svrnm** [comment]
I prefer Option 2, since we should limit the number of banner entries, 2 is what we do max right now.

Would you mind raising a PR for this such that we can see a preview of that? Maybe add some outdated example entries and some examples in the future to see the logic working. 

Note that we do not assign issues, just raise the PR and by that you are the one working on that.

@chalin wdyt?

**Comment by chalin** [comment]
Overall, I prefer option 2, but with these changes:

- Banner YAML entries of the following form:
    ```yaml
    - text: Some markdown text possibly with HTML
      from: <some-date> # optional
      to: <some-other-date> # also optional
    ```
- Keep banner data as close to where it is displayed, so I'd suggest putting it in the front matter of `content/en/_index.md` as a field named something like `banners`.

Thoughts?
