### ISSUE TITLE
Building a custom collector

### ISSUE THREAD

**Issue by vernonr3** [open-telemetry/opentelemetry.io#5259]
The build instructions for using ocb at version 110.0 don't work.

The builder-config.yaml is
dist:
  name: otelcol-dev
  module: github.com/open-telemetry/opentelemetry-collector
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: "0.110.0"
  version: "0.0.1"

exporters:
  - gomod:
      # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
      go.opentelemetry.io/collector/exporter/debugexporter v0.110.0
  - gomod:
      go.opentelemetry.io/collector/otlpexporter v0.110.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.110.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.110.0

The response to:
./ocb_110 --config builder-config.yaml

is

2024-09-27T17:04:19.796+0100	INFO	internal/command.go:125	OpenTelemetry Collector Builder	{"version": "(devel)"}
2024-09-27T17:04:19.797+0100	INFO	internal/command.go:161	Using config file	{"path": "builder-config.yaml"}
2024-09-27T17:04:19.797+0100	INFO	builder/config.go:142	Using go	{"go-executable": "/snap/bin/go"}
2024-09-27T17:04:19.798+0100	INFO	builder/main.go:101	Sources created	{"path": "./otelcol-dev"}
Error: failed to update go.mod: go subcommand failed with args '[mod tidy -compat=1.22]': exit status 1, error message: go: downloading go.opentelemetry.io/collector/confmap/provider/fileprovider v0.110.0
go: downloading go.opentelemetry.io/collector/otlpexporter v0.110.0
go: downloading go.opentelemetry.io/collector/confmap/provider/envprovider v0.110.0
go: go.opentelemetry.io/collector/confmap/provider/envprovider@v0.110.0: reading go.opentelemetry.io/collector/confmap/provider/envprovider/go.mod at revision confmap/provider/envprovider/v0.110.0: unknown revision confmap/provider/envprovider/v0.110.0

Am I right in thinking there are versioning issues?

Thanks

**Comment by svrnm** [comment]
@open-telemetry/collector-approvers PTAL

**Comment by tiffany76** [comment]
Possibly related to https://github.com/open-telemetry/opentelemetry-collector-releases/pull/665.

**Comment by mx-psi** [comment]
Hey, we are looking into a more hands-free approach but what we should do for now is add this to the manifest:

```yaml
providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.16.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.16.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v0.110.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v0.110.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v0.110.0
```
