### ISSUE TITLE
[Page feedback]: Add example of configuring receivers for TLS

### ISSUE THREAD

**Issue by jcranfordbeyondtrust** [open-telemetry/opentelemetry.io#5853]
### URL

https://opentelemetry.io/docs/collector/configuration/#setting-up-certificates

### Description

Include example of how to configure receivers for TLS.

I see examples for exporters but not receivers.

**Comment by tiffany76** [comment]
Thanks for raising these issues, @jcranfordbeyondtrust! We appreciate the detailed and constructive feedback.

@open-telemetry/collector-approvers, PTAL. Thanks.

**Comment by jpkrohling** [comment]
Here's the Collector documentation page with this:

https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/README.md#server-configuration

We have this in the documentation page from this report:
```yaml
  otlp/jaeger:
    endpoint: jaeger-server:4317
    tls:
      cert_file: cert.pem
      key_file: cert-key.pem
```

The counterpart on the receiver side would be this:

```yaml
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls:
          cert_file: cert.pem
          key_file: cert-key.pem
      http:
        endpoint: 0.0.0.0:4318
```
