### ISSUE TITLE
Cap of Go auto-instrumentation

### ISSUE THREAD

**Issue by dzy176** [open-telemetry/opentelemetry.io#5889]
https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/kubernetes/operator/automatic.md?plain=1#L532C1-L539C4

```yaml
securityContext:
  capabilities:
    add:
    - SYS_PTRACE
  privileged: true
  runAsUser: 0
```

If a container is already privileged, what is the purpose of explicitly adding SYS_PTRACE?
