### ISSUE TITLE
Use YAML for the site config

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#714]
TOML makes sense for _really_ simple config files, but when there too much nesting, folks end up using indentation like the follow (which is just begging for YAML IMHO):

```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"
```

YAML will be easier to read.
